[build]
  # Tell Netlify your app lives in frontend/
  base = "frontend"
  command = "npm ci && npm run build"
  publish = "dist"

[functions]
  # Functions live at repo-root/netlify/functions
  directory = "netlify/functions"
  node_bundler = "esbuild"
